# -*- coding: utf-8 -*-
"""Actividad1+BarbaraSanchez

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUcNLVnRAl5AUHpjBjHzfm7zRFWFCpH6
"""

# Pedimos las dos notas
nota_1 = float(input("Ingrese la primera nota: "))
nota_2 = float(input("Ingrese la segunda nota: "))

# Calculamos la nota final
nota_final = (0.4 * nota_1) + (0.6 * nota_2)

# Mostramos el resultado
print(f"La nota final es: {nota_final}")